-- 코드를 입력하세요
# BOOK, AUTHOR
# BOOK: BOOK_ID, CATEGORY, AUTHOR_ID, PRICE, PUBLISHED_DATE
# AUTHOR: AUTHOR_ID, AUTHOR_NAME
# BOOK_SALES: BOOK_ID, SALES_DATE, SALES

# 2022년 1월의 도서 판매 데이터 기준, 저자 별, 카테고리 별 매출액(판매량 * 판매가) 구해서
# AUTHOR_ID, AUTHOR_NAME, CATEGORY, SALES 출력
# 저자 ID ASC, 카테고리 DESC

# 3. 합치기
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES BS
JOIN BOOK B ON B.BOOK_ID = BS.BOOK_ID
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE <= '2022-01-31'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC

# SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, AS TOTAL_SALES
# FROM *
# WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE <= '2022-01-31'
# GROUP BY AUTHOR_ID, CATEGORY
# ORDER BY AUTHOR_ID, CATEGORY DESC
