SELECT E.ID, E.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA E 
JOIN (SELECT P.ID, P.GENOTYPE
         FROM ECOLI_DATA P
         ) AS P
WHERE E.PARENT_ID = P.ID AND 
    (E.GENOTYPE & P.GENOTYPE) = P.GENOTYPE
ORDER BY ID;