-- 코드를 작성해주세요

# 2022년도 한해 평가 점수(상+하반기 점수의 합)이 가장 높은 사원의 정보


# HR_GRADE에서 조회
SELECT SUM(SCORE) AS SCORE, HE.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES HE
JOIN HR_GRADE HG ON HE.EMP_NO = HG.EMP_NO
GROUP BY HE.EMP_NO
HAVING SUM(SCORE) = (
SELECT MAX(TOTAL)
FROM (
SELECT SUM(SCORE) AS TOTAL # -> 5개의 열, 이 중에서 MAX 찾기
FROM HR_GRADE
GROUP BY EMP_NO, YEAR) AS T
) 