-- 코드를 입력하세요

# FIRST_HALF : SHIPMENT_ID, FLAVOR(키), TOTAL_ORDER
# ICECREAM_INFO: FLAVOR(FIRST_HALF의 외래키이자 ICECREAM_INFO의 기본키), INGREDIENT_TYPE:SUGAR_BASED / FRUIT_BASED

# 각 아이스크림의 성분 타입과, 성분 타입에 대한 아이스크림의 총 주문량을 오름차순으로


# FIRST_HALF에서 FLAVOR별로 묶으면 TOTAL_ORDER의 합이 나옴
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F
JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER
# 1. F와 I를 조인 -> 이제 각 FLAVOR의 성분과 TOTAL_ORDER를 알수 있음
# 2. GROUP BY로 INGREDIENT_TYPE으로 묶음 -> 이제 SUGAR_BASED의 TOTAL_ORDER와 FRUIT_BASED의 TOTAL_ORDER로 나뉨
# 3. 출력
# ??