select B.TITLE, R.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
from USED_GOODS_BOARD B
join USED_GOODS_REPLY R
on B.BOARD_ID = R.BOARD_ID
where (B.CREATED_DATE >= '2022-10-01' AND B.CREATED_DATE <= '2022-10-31') OR
(R.CREATED_DATE >= '2022-10-01' AND R.CREATED_DATE <= '2022-10-31')
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;