-- 코드를 입력하세요
# SELECT
# FOOD_PRODUCT: PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
# CATEGORY = '과자' OR '국' OR '김치' OR '식용유'
# ORDER BY PRICE DESC
# CATEGORY로 묶으면: 과자, 국, 김치, 식용유, ~~~
# 이중에서 CATEGORY가 '과자' OR '국'... 일때, GROUP BY의 MAX_PRICE와 같은 PRICE라면 출력?
# 김치 카테고리에서 제일 비싼거, 식용유 카테고리에서 제일 비싼거... 

# SELECT CATEGORY, MAX(PRICE) OVER (PARTITION BY CATEGORY) AS MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유'
# GROUP BY CATEGORY
# ORDER BY PRICE DESC

SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY)
ORDER BY PRICE DESC